version: '3.7'

# This file is intended to be used as an override file
# for creating the development environment

services:
    
    autocomplete-client:
        build: ./autocomplete-client

    autocomplete-service:
        build: ./autocomplete-service

volumes:
     notused:
              