services:
    - docker

before_install:
    # Build the development image for the Autocomplete Client
    # and the standard image for the Autocomplete Service
    - docker build -t nvisal1/autocomplete-client-test -f autocomplete-client/Dockerfile.dev autocomplete-client
    - docker build -t nvisal1/autocomplete-service autocomplete-service

script:
    # Run all unit tests by overriding the CMD for both images
    - docker run -e CI=true nvisal1/autocomplete-client-test npm test
    - docker run nvisal1/autocomplete-service npm test

after_success:
    # Build the production image for the client
    - docker build -t nvisal1/autocomplete-client -f autocomplete-client .

    # Login and push the production client image and
    # standard service image to Dockerhub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"

    - docker push nvisal1/autocomplete-client
    - docker push nvisal1/autocomplete-service