services:
    - docker

before_install:
    - docker build -t client-test -f autocomplete-client/Dockerfile.dev autocomplete-client
    - docker build -t nvisal1/autocomplete-service autocomplete-service

script:
    - docker run nvisal1/autocomplete-client-test npm test
    - docker run nvisal1/autocomplete-service npm test

after_success:
    - docker build -t nvisal1/autocomplete-client -f autocomplete-client .
