version: '3.7'

services:
    
    autocomplete-client:
        build: ./autocomplete-client/Dockerfile.dev.yml

    autocomplete-service:
        build: ./autocomplete-service
        ports:
            - "5000:5000"
        restart: on-failure
    
volumes:
     notused:
              