version: '3.7'

services:
    
    autocomplete-client:
        build: 
            context: ./autocomplete-client
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        restart: on-failure
        
    autocomplete-service:
        build: ./autocomplete-service
        ports:
            - "5000:5000"
        restart: on-failure
    
volumes:
     notused:
              